#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// 1. Charger l'autoloader pour que PHP connaisse les classes Laravel
require __DIR__.'/vendor/autoload.php';

// 2. Initialiser l'application
$app = require_once __DIR__.'/bootstrap/app.php';

// 3. Exécuter la console
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);